### ISSUE TITLE
Plausible new concepts

### ISSUE THREAD

**Issue by chanys** [WorldModelers/Ontologies#101]
The following are some of the clusters that I thought might be interesting/useful (mined from the ~400 CDRs), and I'm trying to see whether folks are interested in adding some of them as new nodes. The clusters are automatically obtained, so the keywords will have to be manually filtered. We can use the first token (e.g. C3) as identifiers.

C3 12.97633009708739 pathogen infectious diseases pathogens pathogenesis pathogenic pathogenicity parasites pneumoniae bacteria bacterial infections enveloped reservoirs viruses susceptibles lethality antigenic pestis viral circulating influenzas spread plagues infectiousness humoral infection virus virulent spreads borne carriers virulence transmitting circulation replication novel immune infected microbes agent modes sepsis fungal serogroup transmission antigens enteric bacterium interacting complications epidemic origination susceptible subtypes epidemics superspreaders salmonella syndrome prone adverse exposure microbe causality mosquitoes latent transmitted influenza pests fungicides variants pesticide influenzae pneumonia naturally resistant
* Are folks interested in adding the above as a new "pathogen" concept (the keywords have to be selected)? The closest seems to be the current concept "vector", but that contains examples "water, mosquitos, excrement, vector, transmission", which seems to be a lot more general. There is also currently a "disease" node, but that's really more like "pandemic". And then there are currently specific disease node: COVID, flu, malaria

C11 10.237441176470597 seminar proceedings presentation lecture symposium topic journal presentations pages papers essay essays participants workshops attendees meeting conference monograph pp founding thesis presented debates perspectives stanford ribbon jama trustees remark talk session slides theme series fellow visiting remarks edited crc convention keynote doctoral chairperson vol discussion review advisors collaborators interview handbook thematic letter panels university thirteenth shared seminars workshop occasional hearing governors flagship credentials rec teleconference college magazine lecturer exhibitions advisory conferences discussants chairs brief ceremony blogs publishers held sponsored briefs convened geneva
* Are the above suitable as a new "dialogue" node under the current "communicate" node?

C14 8.547723076923088 detained sentenced prisoners tortured jailed kidnapped arrests arrested jail exiled custody detainees inmates imprisoned freed prisoner beaten pardons implicated pardoned book injured searches weekdays hiding fired prosecution arrest notorious allegations accused abuses paralyzed amnesty blocks labelled rescued raped whereabouts suspicion incarcerated abducted detention traced captivity torture
* Are we interested in adding a new "justice" node directly under the "process" node? With the filtered keywords: detained sentenced jailed arrests arrested jail exiled custody imprisoned pardons pardoned prosecution arrest allegations accused amnesty incarcerated detention captivity

C16 8.018653061224486 ore nickel aluminum aluminium zinc cobalt quarry mining coal ores timber vanilla metals metal copper rubber mineral charcoal glass mechanics armaments copperbelt coconut acid precious petroleum merchandise cocoa extractives diamond gold rand factory concentrates diamonds stones cement minerals
* Are we interested in grounding to a new "metal" node?

C17 8.006409090909093 buildings families residences dwellings homes houses shelters premises dwelling housing homesite spaces facades residential roofs towns accommodation settlements centres bars dormitories apartment halls home accommodations titles parents mines residency lives bathrooms lifesaving kitchens trees eyes floors street liberties house wards makeshift siblings rooms belongings neighbours firewood grandchildren windows towers tents inhabitants bills living backs everything sites people camps property shelter villages amenities furniture infrastructures extensions
* Are we interested in grounding to a new "building" node under current node "infrastructure"?

C18 7.953610169491528 disinfect disinfected disinfecting disinfectants disinfectant disseminating deworming resour reusable thermometer handwashing disable sanitizer bleach detergents dispensers distancingmay disinfection countermeasure sprays sanitizing defecation reagent spray durability antiretroviral disseminates agent chlorination sanitizers dilution sprayers antimicrobial refrigerated sprayer antibacterial disposable diluted thermometers diagnosing instill decongestion reagents
* We have a "hyginene_materials" node. Are we interested in a new (process) "sanitize" or "disinfect" node under current node "medical"?

C20 7.734534883720933 ballot polling votes seats polls elections voter electorate electoral voting constituency election victory legislature strongmen politics cast speaker credentials referendum alliances politicians legislators party parties parliamentary constituencies seat constituents contest governing campaign assemblies
* Are we interested in a new "legislative_body" node, under current node "entity"? (the above keywords have to be filtered) 

C21 7.448064516129027 lab testing testbeds laboratories laboratoryconfirmed laboratory evidencebased diagnostic experiment diagnostics scientist trial experimentalis isolates experiments investigational scientific labs tests experimental cultured studies samples negatives randomized scientifically positives modelers clinical scientists dilutions operating random specimens specimen suspect empirical reference routine trials tested postdoctoral research observational elisa clinically investigators
* Are we interested in a new "clinical_trial" node under current node "medical"?

C24 6.475754716981133 vehicle cars vehicles buses taxis bike bicycle petrol truck motorbikes motorcycle foot motorized taxi motorbike parked trucks tractors luggage train bus intercity fruits boats helicopter ambulances music motor cards auto boat car lanes vans cycling modes gear ids
* These are "vehicles". Are folks interested in having this as a new node, or as additional keywords under the current "personal_transportation" node?

C40 5.414444444444442 diplomat delegation embassy diplomats envoy ambassador assistant administrator ministerial adviser president diplomacy diplomatic abroad politics gateway visited deputy chamber ministere advisor bilateral correspondent coordinator representation resident border spokesman secretary missions representative allies
* Are we interested in a new "political_agent" node?

C42 4.911842105263156 students pupils learners classrooms graduates sophomore tuition applicants children student classes peers graduation learner members teacher qualifications youths kindergarten exams subjects daughters schoolchildren dropouts adolescents admissions junior winners repetition youth graduated
* Are we interested in a new "student" node?

C45 4.714030303030306 lockdowns shutdowns lock lockdown shutdown lawlessness closings closures shutting closure blockade layoffs cessation masks outages crackdowns safeguarding shuttered unlocking stoppage cordon stopover shut
* We currently have "quarantine" and "social_distancing" nodes in the ontology. Are the above shutdowns/lockdowns one of these, or something different?

C46 4.680843749999999 disabilities homeless transgender disabled disability wheelchair blind transgenderism diabetes child physically visually selfemployed homelessness paralyzed mentally elder stroke hearing blindness specialised orphans older veterans impairments
* Are we interested in a new "disabled_persons" node?

C47 4.660964285714286 accept negotiation negotiate agreeing signed ratification adopted approve go deal honor sign brokered agreed agree repeal arrange agreement rapprochement signing adhere decided embark
* Not sure whether we are interested in this cluster. We currently have a "debate" node. Are these negotation/brokered belonging to this "debate" node, or something different.

C49 4.247181818181817 postponement postponing overdue deferred postpones expire postpone go falter beforehand ahead ending shortly during notify last expiration elapsed until unilateral precipitously onward deferring imposition till withheld indefinitely
* Are we interested in a new node "postphone" or "defer"?

C50 3.910088235294115 troops military fighters generals defence hostilities stationed escorts troop forces soldiers peacekeeping occupied militants colonel missiles war paramilitary units veteran rebels scouts operations actors civilian hands militias wounded missile
* Are we interested in a new node "fighting_unit" or something similar?

Are Alli and Lucian in this repo?

tag @BeckySharp @MihaiSurdeanu

**Comment by zupon** [comment]
Closed by #115
