### ISSUE TITLE
Plausible new keywords for current concepts

### ISSUE THREAD

**Issue by chanys** [WorldModelers/Ontologies#102]
C15 8.124886363636366 bull oxen ox cattle animals cows bulls goats calves livestock tractor hides cow dog horses donkeys ruminants goat vet camel chat horse barley pig pigs animal hay calf skins browse pork
* A "livestock" node already exists in current WM ontology, we could add these filtered keywords: bull oxen ox bulls calves horses donkeys camel horse calf

C19 7.890490196078414 theft robberies robbed assault robbery kidnapping thefts abduction intimidation crime corruption looting shootings criminality vandalism riot smuggling terrorism assaults bullying suicides killings begging harassment erosion neglect abuses crimes gang disappearances suicide fights accidents violence possession copying perpetrators violations raped laundering violent
* Additional keywords for the current "crime" node: robberies robbed robbery kidnapping thefts abduction intimidation corruption criminality vandalism smuggling terrorism? harassment abuses crimes raped laundering

C23 6.579104166666673 supermarkets supermarket grocery groceries shopping retailers shops restaurants bakery stores cafes pastry retailing diners bazaar outlets industries trades store amazon substitutes marketplaces bananas tomato weekends shop eateries canteens retail staples wholesale price convenience merchants
* Will the above be keywords for "physical_market"?

C27 6.298774193548391 paracetamol dexamethasone methylprednisolone aspirin antimicrobials orally corticosteroid chloroquine hypoxemia antiretroviral procalcitonin mmr therapeutic diphtheria chemoprophylaxis aspartate infusions contraindications dmem antiviral glaxosmithkline penicillin steroids corticosteroids fbs
* Probably some of the above as additional keywords to the current "medicine" node?

C28 6.198982142857141 reporters reporter journalist analysts correspondents journalists musicians operatives pressers delegates bloggers media writer newsethiopia tribune acting deputy publisher servant consultancy correspondent programming leaders headlines scouts insight worker news singer investigative editor administrators spokesman reporting analyst broadcasts heroes defenders supervisors communications broadcasting artists officers
* Additional keywords for "person_or_group"?

C34 6.037520000000006 budgets spending grants funding funds budgeting contributions backing funders funder budget programs financing fund spent contracts financial invest revenues block billion requirements efforts schemes powers spends resources subsidies policies philanthropic assistance generosity costed finance appropriations donations thereof towards budgetary
* Should some of these be additional keywords under the current "budget" node?

C35 6.036638888888891 electrical grid generator electric electrification electricity fuelwood lighting powered solarization piped backup generation complements charging connected power charge traction utility analog motor solar hydroelectric renewable smoke
* Should some of these be additional keywords under the current "electrical_infrastructure" node?

tag @BeckySharp @MihaiSurdeanu

**Comment by BeckySharp** [comment]
thanks @chanys  !
 
I vote yes to all except for the `budget` suggestions, I think only a subset of these should go under budget, and perhaps we need a `spend` event?

**Comment by zupon** [comment]
Closed by #115
