### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by lgalescu** [WorldModelers/Ontologies#107]
in today's mtg i finally understood (hopefully) that the so-called examples are actually meant as seeds for computing some kind of embedding -- in other words, they were meant to be consumed by specific kinds of algorithms. had that been made explicit from the start, it would have prevented a lot of misunderstandings (not only mine, but, as we all saw, in the CauseMos team, as well). i suggest renaming the "examples" attributes to "seeds" or something similar.

**Comment by kwalcock** [comment]
Partially addressed in #156.
