### ISSUE TITLE
Sentiment clusters mined from subset of P3 documents

### ISSUE THREAD

**Issue by chanys** [WorldModelers/Ontologies#112]
Not sure whether sentiment clusters will be useful in the WM ontology

16.24112121212121 728 empathy compassion tolerance sympathy goodwill forgiveness camaraderie pain healing forgive emotion solidarity calm hearts bonding humanity patience comfort responsibility conscience affinity sympathetic guilt inspiration creativity friendship accountability acceptance belonging courage pride appreciation loyalty differentiation resiliency integration gratitude comprehension happiness harmony amnesty approachable optimism coping dignity faith tears respect helpful motivation depression resolute minds heroism functionality loving identity hatred kindly clarity ship altruistic listener tolerant understandings sensitivity devotion strength kinship consciousness respectfully responsiveness wounds respectful spirituality attachment character supportive relief friendless closure memory bond meaning sadness saving resilience hopeful safety truth awareness distanced confidence cares discipline emotions love
* 0 728 positive feelings
* New node: Property->Support; Keywords: empathy, goodwill, camaraderie, solidarity, affinity

7.154425000000001 291 resentments frustrations anger frustration discontent resentment discontents disappointment paranoia disappointments rage troubles mistrust pains discomfort dilemmas fatigue negatives contentions distrust oppositions fears attachments compromises doubts
* Existing node: Concept->Crisis_or_Disaster->Conflict->Tension; Keywords: resentments, discontents, mistrust, frustrations

tag @jmacbrid @zupon @BeckySharp @MihaiSurdeanu

**Comment by zupon** [comment]
Closed by #115
