### ISSUE TITLE
Probably somewhat less useful clusters mined from subset of P3 documents

### ISSUE THREAD

**Issue by chanys** [WorldModelers/Ontologies#113]
21.70160000000005 132 substantiated infer substantiate pinpoint hypotheses conclusively corroborated exaggerate anecdotal corroborate contradict correlate estimating substantiates posits counterfactual clarification underscoring hypothesized credence inconclusive base alluded conclusive attribution really plausibly hypothesize infers purview reframed observable hypothesizes discerned posit affirms surpasses discern caveats herself extrapolating bolstered extrapolated corroborating surmise underscored correlates contradicts contemplate credibly versa primer ascertain derived construed bode complicate underestimate epidemiological taken reliably circumscribed evoked zero negligible invoke simplistic based affirmation vice suffice dispel counterweight cussed amplify refuted counterintuitive resonate al extents sceptical outlining appreciating applicability simplify comprehend purport salient overtly ruled pertain overtaken catalyzed underscore verifiable diazepam abound glean alluding debunk attributable disentangle square is inject acculturation spective disparity decipher accumulating observational subsumed distort puzzling elicited outweigh intangible subscribe plentiful invokes proof affirming underline overestimate outlier hitherto predate firsthand etc gleaned sidelines expounded conflate underscores measurable
* 0 132 substantiate, corroborate
* New node: Process->Substantiate; Keywords: ?? (there seems to be several clusters in the processed documents that have to do with experimentation trials)

15.674905263157914 706 randomized sample randomization statistically controlled experimental empirically pooled clinical dataset trial experiments trials randomised control study factorial randomly random experiment concerted statistical epidemiological questionnaires observed average consensus sporadically evidence observational datasets systematic rigorously longitudinal et causation experimenta data statistic sampling observable correlation surveys matching velopment survey correlations fieldwork empirical epidemiology covariates observation assignment samples qualitative posited
* 0 706 scientific experiment terms
* Existing node: Process->Research; Keywords: study, survey, observe, experiment, trial

21.383304347826112 734 discussed illustrated outlined summarized aforementioned brackets summarises summarizes follows below detail summaries written summarize above exhaustive offered columns diagram summarised shown revisited illustration description table upper simplicity infographic listed parentheses described sorted briefly grouped correspond basics illustrates illustrate overview complete cited scribed graph succinct outline graphically detailed visual following overviews begin elucidate arrows referenced underlined provides footnote chart hereafter concise graphs checklist elaborated list quote primer here broken presenting illustrating traces depiction corresponding contained quadrant illustrations immediately visualize sets depicts figure sheets laid considered earlier outlining sheet preceding summary extracted demonstrate reiterate subsequently presented touched
* 1 734 Process->Communicate
* New node: Process->Communicate->Describe; Keywords: discussed, outlined, summarized, description, illustrates

16.595612676056373 700 advisor consultant coordinator adviser consulting deputy specialist director head advisory manager envoy tank coordinators officer chair senior staffer counsel trip junior technical expert testimony inc oftransition fellow assistant briefing advisors group researcher counsellor consultancy analyst committee hired contracted ambassadors predecessor sponsor chairman chief chaired chairperson background professor administrator paralegals leader founder today representative branch headquarters focal lecturer consultants washington inspector joined website contributor prosecutor trainer ant leadership briefs assistants commissioner associates associate acting counterparts visiting
* 0 700 person roles (e.g. advisor, consultant)
* Existing node: Entity->Person_or_Group
* Or a new node "advisor" under Person_or_Group, but might not be very useful

tag @jmacbrid @zupon @BeckySharp @MihaiSurdeanu

**Comment by zupon** [comment]
Closed by #115
