### ISSUE TITLE
Trend like clusters mined from subset of P3 documents

### ISSUE THREAD

**Issue by chanys** [WorldModelers/Ontologies#114]
16.14299999999996 212 decreases reduces improvements increases decrease drops risen decreased decreasing grows fewer varies improves declines persists doubled increase becomes rise reduction lower shrink dropped lasts increased shifts substantially double decline less lowers rises exponentially stays climbed upsurge recur improved uptick stayed influences differed happens loses positively losers goes converts drop contributes differs rising waned follows consistently fall farther compounds affects diminish passes declined dissipate falls reduced changes lowered leads variations rose ranges amplifies reduce occurs takes correlated
* 0 212 change in value (decreases, increases)
* New node: Process->Increase; Keywords: rise, grow, improve, double, climb, upsurge, uptick (possibly same as Process->Develop?)
* New node: Process->Decrease; Keywords: reduce, decline, shrink, drop, waned, diminish

8.949208333333322 447 deteriorating deteriorated declining weakest poorer deterioration demise worsening depressed tightening slipping booming waning falling devaluation disadvantage collapse trapped heightened changing weakening decreasing downfall slackened breakdown eroded disadvantageous soured turbulent low struggling weak aging weakness diminished collapsed fledgling declined reversed halving volatility rising weakened unstable shock normalised strained bleak closing erosion turbulence diminishing
* New node: Process->Decrease; Keywords: declining, deteriorated, waning, collapse, dimished

35.46375 232 exacerbates exacerbation exacerbating exacerbated exacerbate repercussions erode aggravate escalate eroding inflict erupt emboldened ramifications intensifies endangering accrue endanger upheaval aggravating mitigation complicate inflame intensifying appease perpetuates stressors mitigated proximate conducive prolong intensify exogenous escalation unleash ebola worsens escalating underpinned alleviation outweigh root perpetuate endogenous inflicting escalates deleterious begetting equate intensification underlie undermining defuse alarmingly impediments uptake instil externalities magnifying pave impede impeding entrench prolonging engender infusions spillover perpetuating preclude underpinning subsides consequential inflicts incur gases forestalling intractable illuminate symptom environ complicates causes exerted existential alleviating resonate exigencies underpin overburden adverse forestall obstruct animate precipitate equalizer afflicted uploading perverse expedient equitably deficiencies cohort added ameliorate inundating magnified attorney consequence propensity aspire depressing epicentre bigger distorts equitable opportune emblematic degrade engendered mutilation heightens culprit reinforcing elevate nourished capitalize adversely excruciating hasten ignite protracted giving underlying instigate entailed nomic aggravates irreversible eradicated heighten reliant stressor insulate pervasive impacting hindrance disruptive immune pose susceptibility worsening inroads potentially unsustainable potency bedevilling constrain prolongs entrenched costing buttressed systemically disparities incentivize elicited engenders source insecure negligible putting especial bolstering troubling responsible brunt avert retarded propel aggravated ingrained anxieties determinants precipitated exerting proliferating catastrophic eschew degrading devastating predate product indulge multiplier annum averting ensuing cycles sources endorsing amplify jeopardise impeded underscored relapsing inevitably prosper mitigates inflaming exert advantage reverberate perpetuated allocating immunization initiators undercut inherent feeding compel consequent arising into frustrates could amplifying erupting burgeoning elicit absorptive backfire isolating epidemiology derailed reinvested sow accentuated effect overload capitalizes elicits attributable overburdened operandi exxonmobil entrenching types worse catalyze forestalled unfold either compromising pitfalls indebted wake necessitate impedes transcends
* 0 232 exacerbate, worsen
* New node: Process->Exacerbate; Keywords: aggravate, escalate, intensify, complicate, inflame

31.58803680981585 93 promoting improving enhancing through expanding foster fostering maintaining building enhance strengthening boosting sustaining helping build strengthens encourage stimulate advancing ensure realizing promote raise ensuring investing fostered generating nurture thriving facilitating facilitated consolidate maximizing saving upholding maximize furthering encouraging strengthen create organizing emphasizing maximise usher promoted enhanced secure popularise protecting via enforcing instituting attaining maintain speed incorporation offering introducing enlisting laying creation rebuild during benefitting nurturing increasing inviting accelerating strengthened promotion initiating supporting driving emphasize integrating accelerate rebuilding undertaking facilitate intensifying encouragement anticipation enabled publicising sustain stronger scaling adding creating flourish engender inform paved garnering instilling aiding enhancement performing become within exposing doubling launching assist pursuit anticipating demonstrating boost benefitted engaging inspire lead seeing formulating initiate cultivated constructing improve amplifying convincing shaping focusing seize spearhead store safeguarding championing positive equip winning sparking opening reflective transforming linking impacting transferring celebrate pushing restoring stabilize fosters stopping achieving reforming them fruitful establishing highlighting share ushering contribute clarifying celebrating our remaining strength generate keeping spreading consolidation involving voluntarily shape sharing recognition deepening sponsor encompassing realise advance increased continuing amplify acting occurring contributing bringing preserving enable obtaining changing champion safeguard expression raising while utilizing including accessing stepped acknowledging nurtures accompanying understanding capturing adopting demonstration increase distribute uphold providing
* 0 93 promote, improve
* New node: Process->Promote; Keywords: promote, improve, enhance, expand, foster, strengthen, boost, sustain, nurture

tag @jmacbrid @zupon @BeckySharp @MihaiSurdeanu

**Comment by MihaiSurdeanu** [comment]
These are great @chanys !
@zupon , @BeckySharp : we should try to expand our set of trigger words based on these.
