### ISSUE TITLE
Remove version number from the ontology file

### ISSUE THREAD

**Issue by bgyori** [WorldModelers/Ontologies#129]
Currently we have `CompositionalOntology_v2.1.yml` with the version number baked into the file. This should probably be avoided since versioning in git is better done using commit hashes, tags, releases, etc. Please voice support or concerns here about whether to go ahead with this.

**Comment by jmacbrid** [comment]
I vote in favor!

**Comment by kwalcock** [comment]
I can make the changes to e.g., build.sbt file and possibly others that are related.
