### ISSUE TITLE
Let me in or connect Travis?

### ISSUE THREAD

**Issue by kwalcock** [WorldModelers/Ontologies#13]
Is there a collaborator on this project who can bump up my status?  I'm trying to get Travis to run unit tests so that we know that the ontology is still valid after edits, but I don't seem to have the authority.  I'm not sure whether admin for the repo is enough.  It might require admin for the account.  I'd also be happy if someone else does it.  The person would have to have a Travis account and then hook it up to this repo.  Thanks!

**Comment by BeckySharp** [comment]
you have admin...
<img width="883" alt="image" src="https://user-images.githubusercontent.com/5384073/59277116-6f891480-8c14-11e9-87c1-c7d0222693b1.png">

**Comment by BeckySharp** [comment]
is it that the repo doesn't support 3rd party stuff currently?

**Comment by brandomr** [comment]
@kwalcock I haven't tried to integrate Travis to a repo in a while so am not sure what we need to do but can try to help troubleshoot today as needed. I will make you an admin for the entire World Modelers organization now to see if that can help resolve things.

**Comment by kwalcock** [comment]
Thanks!
