### ISSUE TITLE
Versioning of ontologies

### ISSUE THREAD

**Issue by kwalcock** [WorldModelers/Ontologies#34]
It has been pointed out that we somehow need to indicate the version of the ontology that is used when reading documents.  In a recent run across the documents I added a version field to the Eidos output and just filled it in manually.  It was the hash code that git uses and looks like "a1a6dbee0296bdd2b81a4a751fce17c9ed0a3af8".

The manual aspect is not maintainable, so I have some changes to be PR'd soon that record this number in code when the jar containing the resource is fetched with jitpack.  It may be that nobody else is using this kind of dependency resolution, but Eidos can then read the version through a function call.  The information could also be placed in a properties file, for example, if some else wants that in addition.

This version number is not immediately useful to humans, so I propose adding a versionDate as well that can give a causual reader of the file an idea of how old the ontology is and help if two outputs have different version numbers to easily identify which is older and things like that.

So, I wonder especially if INDRA will have problems if a new optional versionDate field shows up right under version in https://github.com/clulab/eidos/wiki/JSON-LD#user-content-groundings .

**Comment by bgyori** [comment]
That sounds good, thanks!

**Comment by kwalcock** [comment]
This was addressed with #36.
