### ISSUE TITLE
remove ontology.yaml?

### ISSUE THREAD

**Issue by vanh17** [WorldModelers/Ontologies#4]
Is it being used?  Or an old (now redundant) version?
@MihaiSurdeanu @bnmin

**Comment by MihaiSurdeanu** [comment]
I don't think it's used anymore. It's been replaced by wm.yaml?

**Comment by BeckySharp** [comment]
I think so too -- once @bnmin confirms, @vanh17 you can remove! less is more :)

**Comment by bnmin** [comment]
I think so. Feel free to remove it. @vanh17

**Comment by BeckySharp** [comment]
closed with #6
