### ISSUE TITLE
Add "definition" metadata to the ontology nodes

### ISSUE THREAD

**Issue by BeckySharp** [WorldModelers/Ontologies#42]
Requested during the call with Uncharted + Readers

I think this will be easyish to do in a not-universal-truth kind of way.
fwiw, some of the indicator ontologies we use already have a "description" field.... so at least Eidos supports this.
Perhaps I can add a first draft once the dust settles on the Nov edits (PR #41 ) and a SME can review?

FYI @chanys @MihaiSurdeanu @bnmin

**Comment by zupon** [comment]
Is this closeable? #108 adds a slot for definitions in the ontology and a few example definitions. We don't have definitions for most nodes yet, however.

**Comment by kwalcock** [comment]
IIRC the few definitions were recently renamed description
