### ISSUE TITLE
Possibly incorrect polarity position

### ISSUE THREAD

**Issue by bgyori** [WorldModelers/Ontologies#48]
As I am investigating https://github.com/clulab/eidos/issues/717, I found that the root cause (without going into too much detail about why after various conversions it ultimately results in an error) is a possibly misplaced polarity flag at: https://github.com/WorldModelers/Ontologies/blob/master/wm_metadata.yml#L1711-L1733. If I shift the polarity on line 1733 inwards to be under water_commodity, the error is resolved.
Would making this change be correct? Or am I missing something?

**Comment by kwalcock** [comment]
I think so.  Polarity and name seem to need to be indented the same.
