### ISSUE TITLE
Re-establish an event/entity distinction in the ontology?

### ISSUE THREAD

**Issue by BeckySharp** [WorldModelers/Ontologies#5]
At one point we had a fairly arbitrary split in our ontology for entities/events.  At the time we weren't particularly making use of it.  We are about to start adding a _shallow_ open-domain event-participant component to our grounding, and were thinking that one easy way to do this would be to once-again have this distinction.  
@bnmin -- I am pretty sure that you guys are doing this already -- extracting entities and events that those entities participate in.  Is it ok if we add back this "distinction" (fuzzy though it may be)?  Or will that throw off how you guys are using this shared ontology?
We can do this another way (through metadata or something) -- this just seemed easier

(fyi @MihaiSurdeanu )

**Comment by bnmin** [comment]
I'm not sure about how to differentiate entities and events, especially for vague concepts or general process/state like entities/events. The decision to not differentiate them was a practical one IIRC, because it does not seem to be crucial to distinguish entities and events, but I might be wrong. Happy to discuss possibilities if you could elaborate more. @BeckySharp

**Comment by BeckySharp** [comment]
@bnmin We are wanting to distinguish between concepts which we'd like to associate a participant with (note the _very intentionally_ generic argument name), for example:
can_take_arg:
 - transportation (of X)
 - establishment (of X)
cannot:
 - rainfall
 - immigration

also notice that this is a very fuzzy (and almost entirely pragmatic) distinction.  That is, for sure one could add some arguments to `immigration` (who, from, to, when, why, etc.), but we are simply looking to deepen the representation we are providing the downstream users while not trying to map out all domains of interest (and everything that entails).  Perhaps the distinction is semi along the lines of _transitivity_...?  

If you don't want the change to happen, we can address it internally in a different way too!

**Comment by bnmin** [comment]
It might make sense to not think about the distinction for now, since it's not clear how to make the (pragmatic) distinction for some cases and we both can address the need for deepening the representation internally. This would simplify the ontology work. What do you think?

**Comment by BeckySharp** [comment]
sure!

**Comment by BeckySharp** [comment]
closing thread for now, thanks!
