### ISSUE TITLE
the art and practice of gardening

### ISSUE THREAD

**Issue by lgalescu** [WorldModelers/Ontologies#77]
https://github.com/WorldModelers/Ontologies/blob/25690a258d02fdf1f35ce9140f7cd54145e2b30c/CompositionalOntology_v2.1_metadata.yml#L23

How is "horticulture" like "beets" and "carrots"??? 
I suggest removing "horticulture" as an example, and renaming the type to "vegetables".

**Comment by BeckySharp** [comment]
closed with #83
