### ISSUE TITLE
suggest merging

### ISSUE THREAD

**Issue by lgalescu** [WorldModelers/Ontologies#79]
https://github.com/WorldModelers/Ontologies/blob/25690a258d02fdf1f35ce9140f7cd54145e2b30c/CompositionalOntology_v2.1_metadata.yml#L1526

is there a conceptual distinction between "safety" and "security"? i think these should be merged into a single property. the words themselves are (nearly) synonymous.

**Comment by BeckySharp** [comment]
closed with #83
