### ISSUE TITLE
polarity in ont concepts

### ISSUE THREAD

**Issue by lgalescu** [WorldModelers/Ontologies#85]
https://github.com/WorldModelers/Ontologies/blob/45d9aa80ffcff538dd45f1ff5489ce08072de733/CompositionalOntology_v2.1_metadata.yml#L48

I struggle to understand what a polarity of -1 means when attached to a concept in the ontology. can someone add to the README something about this?

i do understand the concept in extractions (as an aspect of the KR, not of the ontology). for example, i can say "the prices are unstable" and represent that as either using property/stability with polarity -1 or using property/instability with polarity 1 (and for "stable" i would use the same concepts but reversing polarities). in this case the polarity reflects a relation between a particular concept and its realization in an utterance. but in the ontology the latter is missing, which is why i struggle to understand what the polarity sign means there.

unless there's a good reason to keep the polarity in there, i would advocate for its removal.

**Comment by BeckySharp** [comment]
I can add something to the readme (and I'll leave this issue open to ensure I do)
but, the basic idea is that the `polarity` encodes some sense of the inherent "goodness" of the concepts.
The only use for it (and AFAIK eidos is the only reader using it) is to resolve extractions where the final representation depends on an interaction between this inherent "polarity" and the inherent sentiment/polarity of a verb.  This is the example I use to explain it:

To account for this:
- X **worsens** drought 	==> 	X **increases**/promotes dought
- X **worsens** wages 	==> 	X **decreases**/inhibits wages

Essentially, the final polarity of the “node” to be represented in the UI/used in modeling can only be resolved through the combination of the polarity of the concept (here in the ontology) and the polarity of the edge (e.g., "worsen" = NEG and "improved" = POS). Note: as Lucian observed, other discrete values for polarity are possible; they will be added as needed

**Comment by BeckySharp** [comment]
and we're definitely using it, and I am pretty sure that @bgyori is working on incorporating it in INDRA (if he hasn't already).

**Comment by lgalescu** [comment]
so it's just a signal for how these concepts get affected by verbs such as "worsen"?

then why does a "solitary locust" get polarity -1? can you worsen a solitary locust? and does that mean it's increased? a single locust can only increase in size!

[[ha! i finally found a hook to get something off my chest, not about the WM ontology, but about... i don't know, biologists' use of language? wtfh is "solitarious"?? i almost flagged that as some kind of typo, and then i googled it! turns out that hoppers can be "solitarious", the darn critters! i really think biologists should all be forced to use just Latin -- over the last couple of years I've become convinced that English is simply too much for them.]]

**Comment by BeckySharp** [comment]
> so it's just a signal for how these concepts get affected by verbs such as "worsen"?

yes 

> then why does a "solitary locust" get polarity -1? can you worsen a solitary locust? and does that mean it's increased? a single locust can only increase in size!

meh.  we're going for pragmatic > purity, I'd argue that worsened locusts = more locusts...
 
> [[ha! i finally found a hook to get something off my chest, not about the WM ontology, but about... i don't know, biologists' use of language? wtfh is "solitarious"?? i almost flagged that as some kind of typo, and then i googled it! turns out that hoppers can be "solitarious", the darn critters! i really think biologists should all be forced to use just Latin -- over the last couple of years I've become convinced that English is simply too much for them.]]

haha, I agree! :)

**Comment by lgalescu** [comment]
ok, thanks for clearing things up. i know i asked before, but this polarity thing just doesn't seem to stick. i may ask again a couple months hence.

**Comment by BeckySharp** [comment]
:)

**Comment by BeckySharp** [comment]
ok, closing for now, but when you want to ask again we can reopen :D
