### ISSUE TITLE
too specific

### ISSUE THREAD

**Issue by lgalescu** [WorldModelers/Ontologies#86]
https://github.com/WorldModelers/Ontologies/blob/45d9aa80ffcff538dd45f1ff5489ce08072de733/CompositionalOntology_v2.1.yml#L124

can someone explain why we need to make the distinction between post-harvest infrastructure and other infrastructure? i'm not sure that distinction is easy to make (perhaps there are some pieces of infrastructure only used in that stage, but, if so, the distinction is inherent in the concept, we don't need to make it explicit in the ontology). presumably a warehouse can be used just as well in post-harvest and in other stages of production. 

btw, "packaging" is not really an example of infrastructure, but a specific process done in the post-harvest stage. there may be specific facilities for packing/packaging, but i wouldn't know what they would be called.

as a general comment, for these obscure concepts we need domain specialists to give us a better idea of what vocabulary might be mapped to them. i would also like to see examples of real usage. i find the current examples seriously insufficient (more often than not just a spelling out of the concept name).

**Comment by lgalescu** [comment]
even if we do decide to keep "post_harvest_infrastructure", it should be a child type of "farm_infrastructure".

**Comment by lgalescu** [comment]
looking further into this and related concepts, i would suggest adding `.../infrastructure/facility` and mapping all building facilities (barns, warehouses, greenhouses, nurseries, etc.) to that type. i can see that sometimes it is useful to distinguish facilities by their purpose, but do we think it's reasonable to expect any stage of the WM process to distinguish between a case where a warehouse is meant to be used in post-harvest processing vs to store Amazon's products for delivery vs the many other possible uses of warehouses? even words such as "campus" are ambiguous: yes, they often mean a (higher education) school campus, but the word has lately been used more generically for describing industrial facilities (particularly office-type locations, such as in IT).

**Comment by BeckySharp** [comment]
I agree, this is a node that Alli added as a domain expert, but i also highly doubt we can resolve the distinction.

**Comment by BeckySharp** [comment]
found a compromise, merged farm_infrastructure and post_harvest, as I htink we can make the other distinctions

**Comment by BeckySharp** [comment]
closed with #83
