### ISSUE TITLE
alcohol & drugs (& rock 'n roll?)

### ISSUE THREAD

**Issue by lgalescu** [WorldModelers/Ontologies#90]
https://github.com/WorldModelers/Ontologies/blob/45d9aa80ffcff538dd45f1ff5489ce08072de733/CompositionalOntology_v2.1_metadata.yml#L718

maybe "alcoholism", but clearly not just "alcohol", no?

"drugs" by itself also shouldn't map to "substance abuse".

**Comment by BeckySharp** [comment]
closed with #83
