### ISSUE TITLE
Comments and suggestions on the WM ontology v2.1

### ISSUE THREAD

**Issue by lgalescu** [WorldModelers/Ontologies#98]
### terminology on the way I understand how this ontology is structured (by levels):
1.  _root_: `wm_compositional`
    - suggest changing to `wm`
2.  _category_: fixed set of top-level types [`concept`, `entity`, `process`, `property`, `time`]
    - the `/entity/` category is a hodge-podge; i see no objective reason for them not to
      be moved wholesale under `/concept/`
    - ontologists use "concept" and "entity" generically, to apply to all things; i would
      recommend renaming `concept/` to `/object/`, which is more widely accepted usage 
3.  _domain_: only used (somewhat) systematically for the `/concept/` sub-hierarchy
    - there are a few cases of use in the `/process/` hierarchy
4. the lower levels form an is-a hierarchy for the respective domain/process
    - at least this seems to be the general idea; exceptions are probably incidental

### general observations: 
* examples from metadata are a huge mess!
* we probably need a lot more properties -- often it is the modifier that conveys the critical info (eg, "_high_ temperatures" might reduce yields, not just "temperature"; or "_hybrid_ seeds" increase yields, not simply "seeds"). 

### notes on specific nodes:

`wm_compositional/concept/agriculture/disease/crop_disease`
`wm_compositional/concept/agriculture/disease/livestock_disease`
* remove (compositional) -- `/health/disease` should apply to crops, livestock, people, children, whatever (i am not entirely sure how 

`wm_compositional/concept/agriculture/pest/locust/solitary/solitary_hopper`
`wm_compositional/concept/agriculture/pest/locust/solitary/solitary_locust`
`wm_compositional/concept/agriculture/pest/locust/gregarious/hopper_band`
`wm_compositional/concept/agriculture/pest/locust/gregarious/locust_swarm`
* for these four, it seems the intention was to get combos of behavior (solitary
 vs gregarious) with phase (immature vs mature). but the naming is misleading.
* might want to look at grounding data to see if all these are useful or mere
 hair-splitting. if the latter, nodes should be combined.
* if all the distinctions are desirable, i suggest renaming for clarity, using
 separate upper nodes for individuals and swarms/bands:
   `locust/solitary/solitary_hopper` => `locust/immature_locust`
   `locust/solitary/solitary_locust` => `locust/mature_locust`
   `locust/gregarious/hopper_band` => `locust_swarm/immature_locust_swarm` (or _band)
   `locust/gregarious/locust_swarm` => `locust_swarm/mature_locust_swarm`

`wm_compositional/concept/crisis_or_disaster/conflict/crime`
`wm_compositional/concept/crisis_or_disaster/conflict/tension`
* crime is not conflict; tension is typically not a kind of conflict
* neither of them rises to the level of crisis/disaster
* maybe create a "social" domain and put there things like crime, tension, corruption?

`wm_compositional/concept/crisis_or_disaster/disease`
* rename to `epidemic` 

`wm_compositional/concept/crisis_or_disaster/depression_recession`
* rename to `recession` -- a depression is a long recession

`wm_compositional/concept/crisis_or_disaster/evacuation`
* move under `/process/`

`wm_compositional/concept/crisis_or_disaster/taskforce`
* doesn't belong in the crisis/disaster domain
* maybe move under `/entity/person_or_group`?

`wm_compositional/concept/economy/domestic_market`
* rename to `market` or `commerce` (n.b.: there is no `international_market`!)

`wm_compositional/concept/economy/livelihoods/rural_livelihoods`
`wm_compositional/concept/economy/livelihoods/urban_livelihoods`
* rename `livelihoods` => `livelihood`
* is the rural/urban distinction reflected in the data?

`wm_compositional/concept/environment/meteorology/precipitation`
`wm_compositional/concept/environment/meteorology/temperature`
* seems to me that `temperature` is a _property_ of `weather` -- thoughts?

`wm_compositional/concept/environment/meteorology/weather`
* i would replace `meteorology` with `climate` in all the above; or just delete 

`wm_compositional/concept/health/nutrition/malnutrition`
* maybe move under `/disease/` ?

`wm_compositional/concept/health/welfare`
* isn't welfare more general than just health?

`wm_compositional/concept/infrastructure/construction_materials`
* i think this fits better under `/goods/` (they're consumables, not infrastructure)

`wm_compositional/concept/infrastructure/transportation_infrastructure/road_infrastructure`
* too much infrastructure!!!
* rename `transportation_infrastructure` => `transportation`
* rename `road_infrastructure` => `roads`

`wm_compositional/concept/infrastructure/transportation_infrastructure/rail_infrastructure`
* rename `rail_infrastructure` => `railroads`

`wm_compositional/concept/infrastructure/WASH/sanitation_infrastructure`
`wm_compositional/concept/infrastructure/WASH/water_facilities`
* remove `WASH` node

`wm_compositional/concept/migration/human_migration`
* rename to `refugees`

`wm_compositional/concept/migration/IDP`
`wm_compositional/concept/migration/returnees`
* should these three all go under `person_or_group`?

`wm_compositional/concept/physical_market`
* yuck! whoever calls a market _physical_?!? maybe rename to `marketplace`?
* also, it's funny that this appears all alone; maybe move under `/economy/` ?

`wm_compositional/concept/population/demographics/age`
`wm_compositional/concept/population/demographics/gender`
`wm_compositional/concept/population/demographics/race_or_ethnicity`
* remove `demographics` node

`wm_compositional/concept/service/information/surveillance_system`
* `service` only appears in this path -- move concept under `/security/`?

`wm_compositional/concept/storage/agricultural_storage`
* move under `/infrastructure/` (maybe under `farm_infrastructure`?)

`wm_compositional/concept/storage/general_storage_facilities`
* move under `/infrastructure/`

`wm_compositional/concept/storage/household_food_storage`
* very specific! any evidence from grounding data that it is useful?

`wm_compositional/concept/storage/stockpile_goods`
* odd node! any evidence from grounding data that it is useful?

`wm_compositional/concept/trend`
* i'm sure this gets grounded, but is it useful? a trend is a direction of change,
 and those changes ought to be captured by increase/decrease statements

`wm_compositional/concept/water`
* move under `/goods/` ( with food, fuel, etc.)

`wm_compositional/concept/workforce`
* move to the `/economy/` domain

`wm_compositional/process/depreciate`
* there is no opposite process for appreciation in value

`wm_compositional/process/intake`
* is this for food intake? if so, rename to `food_intake` to make it explicit

`wm_compositional/process/population/emigrate`
`wm_compositional/process/population/immigrate`
* these two should be moved under `/migrate/`

`wm_compositional/process/train_or_educate/`
* rename `train_or_educate` => e.g., `teach` (or just `train`)

`wm_compositional/process/train_or_educate/humanitarian_training/emergency_preparedness_training`
* do we expect other subtypes of `/humanitarian_training/`? otherwise remove

`wm_compositional/property/insecurity`
* remove ; should represent as `(security :polarity -)`

`wm_compositional/property/instability`
* remove ; should represent as `(stability :polarity -)`

`wm_compositional/property/nonutilization`
* remove ; should represent as `(utilization :polarity -)`

`wm_compositional/property/unavailability`
* remove ; should represent as `(availability :polarity -)`

`wm_compositional/entity/animal`
* what is this for? `/concept/agriculture/livestock` ought to capture some animals -- is this for everything else? it would be strange to have two subsets of a broad category in two different parts of the hierarchy

`wm_compositional/entity/artifact`
* what is this for? `/concept/goods` ought to capture lots of artifacts

`wm_compositional/entity/geo-location`
* how about just `location`?

`wm_compositional/entity/health_worker`
* a health worker is a person, so it probably should go under `person_or_group`

`wm_compositional/entity/person_or_group`
* wouldn't `people` be more economical?

`wm_compositional/time/season`
* is this really the only temporal concept we need??

**Comment by MihaiSurdeanu** [comment]
Wow! These are great @lgalescu ! Thank you for the effort!

@zupon, @BeckySharp: can you please review and incorporate these changes?

**Comment by MihaiSurdeanu** [comment]
@zupon, @BeckySharp: we can discuss the more difficult ones at the WM project meeting.

**Comment by zupon** [comment]
I can get started on the easier ones now, and we can definitely discuss the hard cases at the WM project meeting.

**Comment by zupon** [comment]
Many of the simpler changes are covered by #99, but there are some specific "hard" cases we wanted to discuss before changing so we don't inadvertently mess something up for someone.

1. Moving `entity/` and/or `time/` inside the `concept/` category. I'm told that BBN might treat these differently, so there may be reason to keep them separate. @chanys does that sound correct?
2. Eliminating redundancy in e.g. `infrastructure/transportation_infrastructure/road_infrastructure/`. Given the whole ontology path, there's a lot of extra `infrastructure` present. If we only see the intermediate node or leaf node (e.g. just `transportation` or just `roads`, per the suggestions), do we lose important information?
3. Things like `crime` and `tension` don't really fit in the `crisis_or_disaster` domain. Should we create a new domain like `social` and move them there, or rename `crisis_and_disaster` to be more inclusive of things like crime and tension?

Some smaller cases to decide on:
- Should we replace `meteorology` domain node with `climate`, delete that intermediate node, or leave it as-is?
- Move `malnutrition` from `nutrition` domain to `disease` domain?
- Keep `entity/animal` node? Is it different enough from `concept/agricultural/livestock`?
- Keep `entity/artifact`, or delete and rely on existing `goods` node?
- In `storage` domain, are nodes like `stockpile_goods` and `household_food_storage` useful?

**Comment by chanys** [comment]
On Q1: It is fine to move `entity` and `time` under `concept`. We don't need them under their own distinct branch. We just need them to be represented somewhere in the ontology, so that we can represent the Event-participants and Event-time. 

On Q2: 
* When doing renaming, ought to ensure that we don't introduce duplicate node names.
* BBN (at least) does not rely on the names of each node to do grounding. But we do rely on the meta-keywords under each node to some extent. So making a branch shorter, doesn't really affect us, so long as the meta-keywords under that node moves along as well.
*

**Comment by zupon** [comment]
Closed by #99
